import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Mono } from 'next/font/google'
import { Lobster_Two } from 'next/font/google'
import Header from './components/header'
import Footer from './components/footer'
import AuthProvider from "@/app/contexts/AuthProvider";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";


export const lobster = Lobster_Two({ weight:"700", subsets: ['latin']})
export const roboto_mono = Roboto_Mono({subsets: ['greek']})

export const metadata: Metadata = {
  title: 'DineEase',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

    const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={ roboto_mono.className + ' container mx-auto bg-slate-200'}>
        <AuthProvider session={session}>
            {children}
            <Footer/>
        </AuthProvider>
      </body>
    </html>
  )
}
